server:
  port: 3000

# springboot数据源配置
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/market?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root  #数据库用户名
    password: 123!@# #该数据库用户的密码
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 20MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:
#    timeout: 10s
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-active: 8
#        max-wait: -1ms

mybatis:  #mybatyis的配置
  mapper-locations: classpath:mapper/*.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  type-aliases-package: com.kdshop.pojo
  config-location: classpath:mybatis/mybatis-config.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志
logging:
  config: classpath:logback.xml

# 上传文件模式：local为本地上传，需要配置下方的imagesPath；imagesPath为你本地图片文件夹路径
#             oss为阿里云上传，需要在阿里云中开通对象存储服务，配置相应的key
uploadMode: local
# 文件上传映射本地路径
# 在项目的源文件夹中建立upload目录，用于文件上传
imagesPath: E:/Code/kd-shop-fast/upload/

# 图片映射地址
fileUploadPathRelative: /images/**